# Generated by Django 3.2.8 on 2021-10-09 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('picts', '0002_image_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='gallery_image',
        ),
    ]
