# Generated by Django 3.2.8 on 2021-10-09 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picts', '0003_remove_image_gallery_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='gallery_image',
            field=models.ImageField(blank=True, upload_to='picha/'),
        ),
    ]
